// <auto-generated />
using System;
using Clean.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clean.Persistence.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20231125100409_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clean.Domain.Entities.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CheckIn");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckInTime = new DateTime(2023, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@doe@email.com",
                            Major = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            CheckInTime = new DateTime(2023, 1, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@doe@email.com",
                            Major = "Computer Science"
                        },
                        new
                        {
                            Id = 3,
                            CheckInTime = new DateTime(2023, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane@doe@email.com",
                            Major = "Computer Science"
                        },
                        new
                        {
                            Id = 4,
                            CheckInTime = new DateTime(2023, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.smith@email.com",
                            Major = "Accounting"
                        },
                        new
                        {
                            Id = 5,
                            CheckInTime = new DateTime(2023, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@email.com",
                            Major = "Finance"
                        },
                        new
                        {
                            Id = 6,
                            CheckInTime = new DateTime(2023, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.jones@email.com",
                            Major = "General Management"
                        },
                        new
                        {
                            Id = 7,
                            CheckInTime = new DateTime(2023, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane@jones@email.com",
                            Major = "Business Analytics"
                        });
                });

            modelBuilder.Entity("Clean.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@doe@email.com",
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane@doe@email.com",
                            FirstName = "Jane",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            Email = "john.smith@email.com",
                            FirstName = "John",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 4,
                            Email = "jane.smith@email.com",
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 5,
                            Email = "john.jones@email.com",
                            FirstName = "John",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 6,
                            Email = "jane@jones@email.com",
                            FirstName = "Jane",
                            LastName = "Jones"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
