// <auto-generated />
using System;
using Handshake.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Handshake.Persistence.Migrations
{
    [DbContext(typeof(HandshakeDbContext))]
    [Migration("20231106113627_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Handshake.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckInTime = new DateTime(2023, 10, 29, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            CheckInTime = new DateTime(2023, 10, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            CheckInTime = new DateTime(2023, 10, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 4,
                            CheckInTime = new DateTime(2023, 11, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 5,
                            CheckInTime = new DateTime(2023, 11, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 6,
                            CheckInTime = new DateTime(2023, 11, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 7,
                            CheckInTime = new DateTime(2023, 11, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 8,
                            CheckInTime = new DateTime(2023, 11, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 9,
                            CheckInTime = new DateTime(2023, 11, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 10,
                            CheckInTime = new DateTime(2023, 11, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Brown"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
